In [ ]:
import torch
import numpy as np

**Tensor Basics**

In [ ]:
x = torch.empty(2, 3, 2)
print(x)

tensor([[[1.3563e-19, 1.3563e-19],
         [4.7261e+22, 8.7529e-04],
         [1.3556e-19, 1.3563e-19]],

        [[1.3563e-19, 1.3563e-19],
         [7.1758e+22, 1.3817e+31],
         [1.1431e+27, 7.1940e+28]]])


In [ ]:
x = torch.rand(2,2)
print(x)

tensor([[0.4781, 0.3297],
        [0.1760, 0.5067]])


In [ ]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
x = torch.ones(2,3)
print(x)
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [ ]:
x = torch.ones(2, 3, dtype=torch.int64)
print(x.dtype)

torch.int64


In [ ]:
x = torch.ones(3,2)
print(x.size())

torch.Size([3, 2])


In [ ]:
x = torch.tensor([2.5, 0.3])
print(x)

tensor([2.5000, 0.3000])


In [ ]:
# basic operations

x = torch.randint(1, 9, (2,2))
y = torch.randint(1, 9, (2,2))

print(x)
print(y)

z = x + y
print(z)
z = torch.add(x, y)
print(z)
y.add_(x)
print(y)

tensor([[6, 7],
        [3, 4]])
tensor([[6, 3],
        [7, 7]])
tensor([[12, 10],
        [10, 11]])
tensor([[12, 10],
        [10, 11]])
tensor([[12, 10],
        [10, 11]])


In [ ]:
x = torch.randint(1, 9, (2,2))
y = torch.randint(1, 9, (2,2))

print(x)
print(y)

z = x - y
print(z)
z = torch.sub(x, y)
print(z)
y.sub_(x)
print(y) # similar with mul and div

tensor([[1, 2],
        [6, 8]])
tensor([[1, 4],
        [7, 7]])
tensor([[ 0, -2],
        [-1,  1]])
tensor([[ 0, -2],
        [-1,  1]])
tensor([[ 0,  2],
        [ 1, -1]])


In [ ]:
# slicing

x = torch.rand(5,3)
print(x)
print(x[1])
print(x[1, :])
print(x[1, 1:3])
print(x[1, 1])
print(x[1, 1].item())

tensor([[0.9942, 0.8056, 0.8774],
        [0.4266, 0.4546, 0.9058],
        [0.0818, 0.7340, 0.3989],
        [0.7065, 0.5444, 0.9786],
        [0.2351, 0.8003, 0.9650]])
tensor([0.4266, 0.4546, 0.9058])
tensor([0.4266, 0.4546, 0.9058])
tensor([0.4546, 0.9058])
tensor(0.4546)
0.4545542597770691


In [ ]:
x = torch.rand(4, 4)
print(x)
y = x.view(16)
print(y)
y = x.view(-1,8)
print(y.size())

tensor([[0.3528, 0.5529, 0.3546, 0.5686],
        [0.6673, 0.2791, 0.8485, 0.6412],
        [0.6369, 0.8842, 0.5226, 0.1934],
        [0.0699, 0.0626, 0.9086, 0.8951]])
tensor([0.3528, 0.5529, 0.3546, 0.5686, 0.6673, 0.2791, 0.8485, 0.6412, 0.6369,
        0.8842, 0.5226, 0.1934, 0.0699, 0.0626, 0.9086, 0.8951])
torch.Size([2, 8])


In [ ]:
# torch to numpy and vice versa

a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
a = np.ones(3, dtype='int')
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)


[1 1 1]
tensor([1, 1, 1])
[2 2 2]
tensor([2, 2, 2])


In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  z = z.to("cpu")
  print(z)

In [ ]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


**Gradient Calculation with Autograd**

In [ ]:
# gradient calculation
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y*y*3
z = z.mean()
print(z)

z.backward() # dz/dx
print(x.grad)

tensor([ 0.4495, -0.2855, -1.4293], requires_grad=True)
tensor([2.4495, 1.7145, 0.5707], grad_fn=<AddBackward0>)
tensor(9.2649, grad_fn=<MeanBackward0>)
tensor([4.8989, 3.4289, 1.1413])


In [ ]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y*y*3
print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float64)
z.backward(v)
print(x.grad)

tensor([-0.7775,  0.5394, -0.5363], requires_grad=True)
tensor([1.2225, 2.5394, 1.4637], grad_fn=<AddBackward0>)
tensor([ 4.4839, 19.3459,  6.4274], grad_fn=<MulBackward0>)
tensor([7.3353e-01, 1.5237e+01, 8.7823e-03])


In [ ]:
# preventing gradient calculation
x = torch.randn(3, requires_grad=True)
print(x)
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad()

# x.requires_grad_(False)
# print(x)

y = x.detach()
print(x)
print(y)


with torch.no_grad():
  y = x + 2
  print(y)



tensor([-0.4564,  0.7741, -2.0622], requires_grad=True)
tensor([-0.4564,  0.7741, -2.0622], requires_grad=True)
tensor([-0.4564,  0.7741, -2.0622])
tensor([ 1.5436,  2.7741, -0.0622])


In [ ]:
# training example
weights = torch.ones(4, requires_grad=True)
print(weights)

for epoch in range(3):
  model_output = (weights*3).sum()
  print(model_output)
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()


tensor([1., 1., 1., 1.], requires_grad=True)
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
