In [48]:
import torch
import numpy as np

**Tensor Basics**

In [6]:
x = torch.empty(2, 3, 2)
print(x)

tensor([[[3.8115e-43, 0.0000e+00],
         [1.7937e-43, 0.0000e+00],
         [4.0042e-41, 0.0000e+00]],

        [[1.5835e-43, 0.0000e+00],
         [6.4086e-34, 0.0000e+00],
         [2.1236e+02, 4.3778e-41]]])


In [11]:
x = torch.rand(2,2)
print(x)

tensor([[0.9097, 0.2659],
        [0.6814, 0.5514]])


In [13]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [16]:
x = torch.ones(2,3)
print(x)
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [23]:
x = torch.ones(2, 3, dtype=torch.int64)
print(x.dtype)

torch.int64


In [24]:
x = torch.ones(3,2)
print(x.size())

torch.Size([3, 2])


In [25]:
x = torch.tensor([2.5, 0.3])
print(x)

tensor([2.5000, 0.3000])


In [35]:
# basic operations

x = torch.randint(1, 9, (2,2))
y = torch.randint(1, 9, (2,2))

print(x)
print(y)

z = x + y
print(z)
z = torch.add(x, y)
print(z)
y.add_(x)
print(y)

tensor([[4, 6],
        [2, 5]])
tensor([[4, 1],
        [2, 4]])
tensor([[8, 7],
        [4, 9]])
tensor([[8, 7],
        [4, 9]])
tensor([[8, 7],
        [4, 9]])


In [36]:
x = torch.randint(1, 9, (2,2))
y = torch.randint(1, 9, (2,2))

print(x)
print(y)

z = x - y
print(z)
z = torch.sub(x, y)
print(z)
y.sub_(x)
print(y) # similar with mul and div

tensor([[4, 1],
        [3, 6]])
tensor([[5, 4],
        [7, 4]])
tensor([[-1, -3],
        [-4,  2]])
tensor([[-1, -3],
        [-4,  2]])
tensor([[ 1,  3],
        [ 4, -2]])


In [43]:
# slicing

x = torch.rand(5,3)
print(x)
print(x[1])
print(x[1, :])
print(x[1, 1:3])
print(x[1, 1])
print(x[1, 1].item())

tensor([[0.5267, 0.1538, 0.0179],
        [0.8543, 0.1712, 0.7654],
        [0.5370, 0.0335, 0.2322],
        [0.9666, 0.6626, 0.1038],
        [0.8092, 0.2090, 0.0610]])
tensor([0.8543, 0.1712, 0.7654])
tensor([0.8543, 0.1712, 0.7654])
tensor([0.1712, 0.7654])
tensor(0.1712)
0.17115139961242676


In [47]:
x = torch.rand(4, 4)
print(x)
y = x.view(16)
print(y)
y = x.view(-1,8)
print(y.size())

tensor([[0.0374, 0.4978, 0.5298, 0.4375],
        [0.9476, 0.4175, 0.8852, 0.2336],
        [0.8924, 0.5710, 0.7007, 0.9671],
        [0.9917, 0.2557, 0.6864, 0.5158]])
tensor([0.0374, 0.4978, 0.5298, 0.4375, 0.9476, 0.4175, 0.8852, 0.2336, 0.8924,
        0.5710, 0.7007, 0.9671, 0.9917, 0.2557, 0.6864, 0.5158])
torch.Size([2, 8])


In [51]:
# torch to numpy and vice versa

a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [61]:
a = np.ones(3, dtype='int')
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)


[1 1 1]
tensor([1, 1, 1])
[2 2 2]
tensor([2, 2, 2])


In [64]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  z = z.to("cpu")
  print(z)

In [65]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
